name: dem-dev
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - compas >=2.8.1
  - ipopt ==3.14.9
  - pyomo ==6.4.2
  - numpy <2.0
  - pip:
      - -r requirements-dev.txt
      - -r requirements-viz.txt
      - -r requirements-analysis.txt
      - -e .
